version: "3"
services:
  postgres:
    image: postgres:9.6.3
    ports:
      - 33339:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments
  users:
    image: rsobnb/payments
    ports:
      - 8086:8086
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://172.17.0.1:33339/payments
    depends_on:
      - postgres