apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: payments-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - image: ggrex/rsobnb-payments:0.1
        imagePullPolicy: Always
        name: payments
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://payments:8086
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-payments:5432/payments
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: dbuser
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: postgres
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://168.1.149.41:32112/
        ports:
        - containerPort: 8086
          name: server
          protocol: TCP